"""Dashboard generation for combining multiple visualizations."""

from datetime import datetime
from pathlib import Path
from typing import List, Optional

from .generator import GeneratedChart


# =============================================================================
# HTML TEMPLATES
# =============================================================================

DASHBOARD_TEMPLATE = '''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        * {{
            box-sizing: border-box;
            margin: 0;
            padding: 0;
        }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
            background-color: #f5f5f5;
            color: #333;
            line-height: 1.6;
        }}

        .header {{
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 2rem;
            text-align: center;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }}

        .header h1 {{
            font-size: 2rem;
            font-weight: 600;
            margin-bottom: 0.5rem;
        }}

        .header .subtitle {{
            font-size: 0.9rem;
            opacity: 0.9;
        }}

        .header .meta {{
            font-size: 0.8rem;
            opacity: 0.7;
            margin-top: 0.5rem;
        }}

        .container {{
            max-width: 1600px;
            margin: 0 auto;
            padding: 2rem;
        }}

        .chart-grid {{
            display: grid;
            grid-template-columns: repeat(auto-fill, minmax(600px, 1fr));
            gap: 1.5rem;
        }}

        .chart-card {{
            background: white;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.08);
            overflow: hidden;
            transition: transform 0.2s, box-shadow 0.2s;
        }}

        .chart-card:hover {{
            transform: translateY(-2px);
            box-shadow: 0 4px 20px rgba(0,0,0,0.12);
        }}

        .chart-header {{
            padding: 1rem 1.5rem;
            border-bottom: 1px solid #eee;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }}

        .chart-title {{
            font-size: 1.1rem;
            font-weight: 600;
            color: #333;
        }}

        .chart-type {{
            font-size: 0.75rem;
            padding: 0.25rem 0.75rem;
            background: #e8e8e8;
            border-radius: 12px;
            color: #666;
            text-transform: uppercase;
            letter-spacing: 0.5px;
        }}

        .chart-description {{
            padding: 0.75rem 1.5rem;
            font-size: 0.85rem;
            color: #666;
            background: #fafafa;
        }}

        .chart-frame {{
            width: 100%;
            height: 500px;
            border: none;
        }}

        .chart-footer {{
            padding: 0.75rem 1.5rem;
            border-top: 1px solid #eee;
            font-size: 0.75rem;
            color: #999;
            display: flex;
            justify-content: space-between;
        }}

        .chart-columns {{
            display: flex;
            gap: 0.5rem;
            flex-wrap: wrap;
        }}

        .column-tag {{
            background: #f0f0f0;
            padding: 0.15rem 0.5rem;
            border-radius: 4px;
            font-family: monospace;
        }}

        .footer {{
            text-align: center;
            padding: 2rem;
            color: #999;
            font-size: 0.85rem;
        }}

        .open-link {{
            color: #667eea;
            text-decoration: none;
            font-size: 0.8rem;
        }}

        .open-link:hover {{
            text-decoration: underline;
        }}

        @media (max-width: 700px) {{
            .chart-grid {{
                grid-template-columns: 1fr;
            }}

            .header h1 {{
                font-size: 1.5rem;
            }}

            .container {{
                padding: 1rem;
            }}
        }}
    </style>
</head>
<body>
    <div class="header">
        <h1>{title}</h1>
        <div class="subtitle">Data Visualization Dashboard</div>
        <div class="meta">Source: {source_file} | Generated: {generated_at} | {chart_count} charts</div>
    </div>

    <div class="container">
        <div class="chart-grid">
            {chart_cards}
        </div>
    </div>

    <div class="footer">
        Generated by Data Analysis Agent Suite
    </div>
</body>
</html>'''


CHART_CARD_TEMPLATE = '''<div class="chart-card">
    <div class="chart-header">
        <span class="chart-title">{title}</span>
        <span class="chart-type">{chart_type}</span>
    </div>
    <div class="chart-description">{description}</div>
    <iframe class="chart-frame" src="{filename}" loading="lazy"></iframe>
    <div class="chart-footer">
        <div class="chart-columns">
            Columns: {columns_html}
        </div>
        <a href="{filename}" target="_blank" class="open-link">Open in new tab ↗</a>
    </div>
</div>'''


# =============================================================================
# DASHBOARD GENERATION
# =============================================================================

def create_chart_card_html(chart: GeneratedChart) -> str:
    """
    Create an HTML card for a single chart.

    Args:
        chart: GeneratedChart object

    Returns:
        HTML string for the chart card
    """
    # Format columns as tags
    columns_html = ' '.join(
        f'<span class="column-tag">{col}</span>'
        for col in chart.columns_used[:5]  # Limit to 5 columns shown
    )
    if len(chart.columns_used) > 5:
        columns_html += f' <span class="column-tag">+{len(chart.columns_used) - 5} more</span>'

    return CHART_CARD_TEMPLATE.format(
        title=chart.title,
        chart_type=chart.chart_type,
        description=chart.description,
        filename=chart.filename,
        columns_html=columns_html,
    )


def generate_dashboard(
    charts: List[GeneratedChart],
    source_file: str,
    output_dir: str,
    title: Optional[str] = None,
) -> str:
    """
    Generate an HTML dashboard combining multiple charts.

    Args:
        charts: List of GeneratedChart objects
        source_file: Name of source data file
        output_dir: Directory to save dashboard
        title: Optional custom title (defaults to source filename)

    Returns:
        Path to generated index.html
    """
    if not charts:
        raise ValueError("Cannot generate dashboard: no charts provided")

    # Default title from source file
    if title is None:
        title = f"{Path(source_file).stem} Dashboard"

    # Generate chart cards HTML
    chart_cards = '\n            '.join(
        create_chart_card_html(chart)
        for chart in charts
    )

    # Generate timestamp
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # Fill template
    dashboard_html = DASHBOARD_TEMPLATE.format(
        title=title,
        source_file=source_file,
        generated_at=generated_at,
        chart_count=len(charts),
        chart_cards=chart_cards,
    )

    # Save to file
    output_path = Path(output_dir) / 'index.html'
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(dashboard_html, encoding='utf-8')

    return str(output_path.resolve())


def generate_dashboard_from_template(
    charts: List[GeneratedChart],
    source_file: str,
    output_dir: str,
    template_path: str,
    title: Optional[str] = None,
) -> str:
    """
    Generate a dashboard using a custom HTML template file.

    The template should contain these placeholders:
    - {title} - Dashboard title
    - {source_file} - Source data file name
    - {generated_at} - Generation timestamp
    - {chart_count} - Number of charts
    - {chart_cards} - HTML for all chart cards

    Args:
        charts: List of GeneratedChart objects
        source_file: Name of source data file
        output_dir: Directory to save dashboard
        template_path: Path to custom template file
        title: Optional custom title

    Returns:
        Path to generated index.html
    """
    # Read custom template
    template = Path(template_path).read_text(encoding='utf-8')

    if title is None:
        title = f"{Path(source_file).stem} Dashboard"

    # Generate chart cards
    chart_cards = '\n            '.join(
        create_chart_card_html(chart)
        for chart in charts
    )

    # Fill template
    dashboard_html = template.format(
        title=title,
        source_file=source_file,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        chart_count=len(charts),
        chart_cards=chart_cards,
    )

    # Save
    output_path = Path(output_dir) / 'index.html'
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(dashboard_html, encoding='utf-8')

    return str(output_path.resolve())
